name: Deploy
on:
  repository_dispatch:
    types: [update_post]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 15.x
      - run: npm run generate
